@baseUrl =  
@authToken = {{authenticate.response.body.accessToken}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "USER MEMBER",
  "email": "usermember@example.com",
  "cpf": "123.456.789-01",
  "phone": "1234567891",
  "password": "12345678",
  "image_url": "http://example.com",
  "role": "MEMBER"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "usermember@example.com",
  "password": "12345678"
}

###

# @name create_animal
POST {{baseUrl}}/pets
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Rex",
  "age": "2020-08-10T00:00:00.000Z",
  "sex": "Male",
  "race": "Golden Retriever",
  "color": "Golden",
  "image_urls": ["https://example.com/rex1.jpg", "https://example.com/rex2.jpg"]
}

###

# @name get_animal
GET {{baseUrl}}/pets
Authorization: Bearer {{authToken}}

###

# @name create_ong
POST {{baseUrl}}/instituation
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Animal 6 Organization",
  "description": "An organization dedicated to helping animals find homes.",
  "image_user": "https://example.com/image.jpg",
  "image_urls": [
    "https://example.com/animal1.jpg",
    "https://example.com/animal2.jpg"
  ]
}

###

# @name get_ong
GET {{baseUrl}}/instituation
Authorization: Bearer {{authToken}}

###

# @name update_ong
PATCH {{baseUrl}}/instituation
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Animal e1q23123 Organization"
}