version: '3.8'

services:
  postgres:
    container_name: petmatch
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
      PG_DATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres